version : "3"
services :
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - "./default.conf:/etc/nginx/default.conf"
    network_mode: host

  shine:
   image: anitha220/app:node-react
   container_name: shine
   restart: unless-stopped
   depends_on:
       - nginx
   ports:
     - "9093:3000"
   volumes:
     - "./app:/usr/share/nginx/html"

